order = [
    "getting-started-in-it-cs-115.md",
    "unit-01.md",
    "unit-01-b.md",
    "unit-02.md",
    "unit-03.md",
    "unit-04.md",
    "unit-05.md",
    "unit-06.md",
    "unit-07.md",
    "unit-08.md",
    "unit-midterm-exam.md",
    "unit-09.md",
    "unit-10.md",
    "unit-11.md",
    "unit-12.md",
    "unit-13.md",
    "unit-14.md",
    "unit-15.md",
    "unit-16.md",

    # "lecture-14-chapter-4-methods-and-parameters.md",
    # "lecture-15-chapter-4-methods-and-parameters-continued.md",
    # "lecture-16-chapter-4-methods-parameters-return-values.md",
    # "lecture-17-chapter-7-introduction-to-arrays.md",
    # "lecture-18-chapter-7-arrays-and-random-numbers.md",
    # "lecture-19-chapter-7-arrays-continued.md",
    # "lecture-20-chapter-7-arrays-continued-part-2.md",
    # "lecture-21-final-exam-review-second-group-activity.md",
    # "lecture-20-final-exam.md",
    # "lecture-21-gui-swing-programming.md",
    # "lecture-21-final-exam-review-ai-llms-and-cybersecurity.md",
]
