order = [
    "getting-started-in-it-cs-115.md",
    "unit-01",
    "unit-02",
    "unit-midterm-exam",

    # "lecture-2-chapter-2-introduction-to-variables-and-expressions.md",
    # "lecture-3-chapter-2-variables-expressions.md",
    # "lecture-4-chapter-3-users-input.md",
    # "lecture-5-chapter-5-conditionals.md",
    # "lecture-6-chapter-5-conditionals-continued.md",
    # "lecture-7-chapter-5-logical-expressions.md",
    # "lecture-08-b-art-arduinos.md",
    # "lecture-8-chapter-5-logical-expressions-continued.md",
    # "lecture-8a-chapter-5-review.md",
    # "lecture-9-chapter-6-iterative-statements-loops.md",
    # "lecture-10-chapter-6-iterative-statements-continued.md",
    # "lecture-11-midterm-exam-review-first-group-activity.md",
    # "lecture-111-chapters-5-6-conditionals-and-loops.md",
    # "lecture-12-midterm-exam.md",
    # "lecture-14-chapter-4-methods-and-parameters.md",
    # "lecture-15-chapter-4-methods-and-parameters-continued.md",
    # "lecture-16-chapter-4-methods-parameters-return-values.md",
    # "lecture-17-chapter-7-introduction-to-arrays.md",
    # "lecture-18-chapter-7-arrays-and-random-numbers.md",
    # "lecture-19-chapter-7-arrays-continued.md",
    # "lecture-20-chapter-7-arrays-continued-part-2.md",
    # "lecture-21-final-exam-review-second-group-activity.md",
    # "lecture-20-final-exam.md",
    # "lecture-21-gui-swing-programming.md",
    # "lecture-21-final-exam-review-ai-llms-and-cybersecurity.md",
]
